name: CD-a

on: 
  push:
    branches:
      - b

jobs:
  build:
    name: "Build-${{ github.ref }}"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Debug
      run: env | sort