name: CD

on: [push]

env:
  SORIN_REF: {{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hello
      run: |
        env | grep GITHUB
        env | grep SORIN
        echo "${SORIN_REF}"
