name: CD

on: [push]

env:
  SORIN_REF: $(echo ${GITHUB_REF} | cut -d '/' -f 3- | cut -d '/' -f 2)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hello
      run: |
        env | grep GITHUB
        env | grep SORIN
        echo "${SORIN_REF}"
