name: CD

on: [push]

env:
  SORIN_REF: $(echo $GITHUB_REF)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hello
      run: |
        env | grep GITHUB
        env | grep SORIN
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
