name: CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hello
      run: |
        env
        uname -a
        pwd
        ls -la
        docker --version
        make --version
        aws --version
        type serverless
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
